/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductPricingService } from "../productPricing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductPricingCreateInput } from "./ProductPricingCreateInput";
import { ProductPricingWhereInput } from "./ProductPricingWhereInput";
import { ProductPricingWhereUniqueInput } from "./ProductPricingWhereUniqueInput";
import { ProductPricingFindManyArgs } from "./ProductPricingFindManyArgs";
import { ProductPricingUpdateInput } from "./ProductPricingUpdateInput";
import { ProductPricing } from "./ProductPricing";
import { Currency } from "../../currency/base/Currency";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductPricingControllerBase {
  constructor(
    protected readonly service: ProductPricingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductPricing",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductPricing })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ProductPricingCreateInput
  ): Promise<ProductPricing> {
    return await this.service.create({
      data: {
        ...data,

        Currency: data.Currency
          ? {
              connect: data.Currency,
            }
          : undefined,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        Currency: {
          select: {
            id: true,
          },
        },

        endingAt: true,
        id: true,
        Price: true,

        product: {
          select: {
            id: true,
          },
        },

        startingAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductPricing",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductPricing] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProductPricingFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<ProductPricing[]> {
    const args = plainToClass(ProductPricingFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        Currency: {
          select: {
            id: true,
          },
        },

        endingAt: true,
        id: true,
        Price: true,

        product: {
          select: {
            id: true,
          },
        },

        startingAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductPricing",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductPricing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProductPricingWhereUniqueInput
  ): Promise<ProductPricing | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        Currency: {
          select: {
            id: true,
          },
        },

        endingAt: true,
        id: true,
        Price: true,

        product: {
          select: {
            id: true,
          },
        },

        startingAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "ProductPricing",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductPricing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProductPricingWhereUniqueInput,
    @common.Body() data: ProductPricingUpdateInput
  ): Promise<ProductPricing | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          Currency: data.Currency
            ? {
                connect: data.Currency,
              }
            : undefined,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          Currency: {
            select: {
              id: true,
            },
          },

          endingAt: true,
          id: true,
          Price: true,

          product: {
            select: {
              id: true,
            },
          },

          startingAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "ProductPricing",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductPricing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProductPricingWhereUniqueInput
  ): Promise<ProductPricing | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          Currency: {
            select: {
              id: true,
            },
          },

          endingAt: true,
          id: true,
          Price: true,

          product: {
            select: {
              id: true,
            },
          },

          startingAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
