/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubscriptionService } from "../subscription.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SubscriptionCreateInput } from "./SubscriptionCreateInput";
import { SubscriptionWhereInput } from "./SubscriptionWhereInput";
import { SubscriptionWhereUniqueInput } from "./SubscriptionWhereUniqueInput";
import { SubscriptionFindManyArgs } from "./SubscriptionFindManyArgs";
import { SubscriptionUpdateInput } from "./SubscriptionUpdateInput";
import { Subscription } from "./Subscription";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SubscriptionControllerBase {
  constructor(
    protected readonly service: SubscriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Subscription",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Subscription })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: SubscriptionCreateInput
  ): Promise<Subscription> {
    return await this.service.create({
      data: {
        ...data,

        invoice: data.invoice
          ? {
              connect: data.invoice,
            }
          : undefined,

        plan: data.plan
          ? {
              connect: data.plan,
            }
          : undefined,

        user: {
          connect: data.user,
        },
      },
      select: {
        cancelledAt: true,
        createdAt: true,
        downgradedAt: true,
        downgradedToPlanId: true,
        endsAt: true,
        id: true,

        invoice: {
          select: {
            id: true,
          },
        },

        plan: {
          select: {
            id: true,
          },
        },

        renewedAt: true,
        renewedSubscriptionId: true,
        startsAt: true,
        updatedAt: true,
        upgradedAt: true,
        upgradedToPlanId: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Subscription",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Subscription] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Subscription[]> {
    const args = plainToClass(SubscriptionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        cancelledAt: true,
        createdAt: true,
        downgradedAt: true,
        downgradedToPlanId: true,
        endsAt: true,
        id: true,

        invoice: {
          select: {
            id: true,
          },
        },

        plan: {
          select: {
            id: true,
          },
        },

        renewedAt: true,
        renewedSubscriptionId: true,
        startsAt: true,
        updatedAt: true,
        upgradedAt: true,
        upgradedToPlanId: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Subscription",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Subscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<Subscription | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        cancelledAt: true,
        createdAt: true,
        downgradedAt: true,
        downgradedToPlanId: true,
        endsAt: true,
        id: true,

        invoice: {
          select: {
            id: true,
          },
        },

        plan: {
          select: {
            id: true,
          },
        },

        renewedAt: true,
        renewedSubscriptionId: true,
        startsAt: true,
        updatedAt: true,
        upgradedAt: true,
        upgradedToPlanId: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Subscription",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Subscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() data: SubscriptionUpdateInput
  ): Promise<Subscription | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          invoice: data.invoice
            ? {
                connect: data.invoice,
              }
            : undefined,

          plan: data.plan
            ? {
                connect: data.plan,
              }
            : undefined,

          user: {
            connect: data.user,
          },
        },
        select: {
          cancelledAt: true,
          createdAt: true,
          downgradedAt: true,
          downgradedToPlanId: true,
          endsAt: true,
          id: true,

          invoice: {
            select: {
              id: true,
            },
          },

          plan: {
            select: {
              id: true,
            },
          },

          renewedAt: true,
          renewedSubscriptionId: true,
          startsAt: true,
          updatedAt: true,
          upgradedAt: true,
          upgradedToPlanId: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Subscription",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Subscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<Subscription | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          cancelledAt: true,
          createdAt: true,
          downgradedAt: true,
          downgradedToPlanId: true,
          endsAt: true,
          id: true,

          invoice: {
            select: {
              id: true,
            },
          },

          plan: {
            select: {
              id: true,
            },
          },

          renewedAt: true,
          renewedSubscriptionId: true,
          startsAt: true,
          updatedAt: true,
          upgradedAt: true,
          upgradedToPlanId: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
