/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { InvoiceLineItemUpdateManyWithoutProductsInput } from "./InvoiceLineItemUpdateManyWithoutProductsInput";
import { Type } from "class-transformer";
import { PlanUpdateManyWithoutProductsInput } from "./PlanUpdateManyWithoutProductsInput";
import { ProductPricingUpdateManyWithoutProductsInput } from "./ProductPricingUpdateManyWithoutProductsInput";
@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceLineItemUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceLineItemUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => InvoiceLineItemUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  invoiceLineItems?: InvoiceLineItemUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => PlanUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PlanUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PlanUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  plans?: PlanUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductPricingUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductPricingUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductPricingUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  productPricings?: ProductPricingUpdateManyWithoutProductsInput;
}
export { ProductUpdateInput };
