/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { InvoiceLineItemCreateNestedManyWithoutProductsInput } from "./InvoiceLineItemCreateNestedManyWithoutProductsInput";
import { Type } from "class-transformer";
import { PlanCreateNestedManyWithoutProductsInput } from "./PlanCreateNestedManyWithoutProductsInput";
import { ProductPricingCreateNestedManyWithoutProductsInput } from "./ProductPricingCreateNestedManyWithoutProductsInput";
@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceLineItemCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceLineItemCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => InvoiceLineItemCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  invoiceLineItems?: InvoiceLineItemCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => PlanCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PlanCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PlanCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  plans?: PlanCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => ProductPricingCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ProductPricingCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ProductPricingCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  productPricings?: ProductPricingCreateNestedManyWithoutProductsInput;
}
export { ProductCreateInput };
